# Generated by Django 4.1.3 on 2023-05-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_welcome_text_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
