# Generated by Django 4.1.3 on 2023-05-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_alter_welcome_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='company_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Şirket adı'),
        ),
    ]
