# Generated by Django 4.1.3 on 2023-05-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_welcome_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True, verbose_name='Şirket adı')),
            ],
        ),
        migrations.RemoveField(
            model_name='welcome',
            name='company_name',
        ),
    ]
