# Generated by Django 4.1.3 on 2023-05-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_company_remove_welcome_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_card_icon', models.CharField(max_length=100, verbose_name='icon')),
                ('detail_title', models.CharField(max_length=100, verbose_name='baslık')),
                ('detail_title_card', models.CharField(max_length=100, null=True, verbose_name='kart baslık')),
                ('detail_text', models.TextField(verbose_name='')),
            ],
        ),
    ]
