# Generated by Django 4.1.3 on 2023-05-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0008_alter_company_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_subtitle',
            field=models.CharField(max_length=100, null=True, verbose_name='Alt yazı'),
        ),
    ]
