# Generated by Django 4.1.3 on 2023-05-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_company_company_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_img', models.ImageField(upload_to='images/', verbose_name='Header-fotoğrafı')),
                ('company_head', models.CharField(max_length=100, null=True, verbose_name='Başlık')),
                ('company_name', models.CharField(max_length=100, verbose_name='Şirket adı')),
                ('company_subtitle', models.CharField(max_length=100, null=True, verbose_name='Alt yazı')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Kadro'},
        ),
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name_plural': 'Hoş Geldin'},
        ),
    ]
