# Generated by Django 4.1.3 on 2023-05-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0011_header_delete_company_alter_team_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcome',
            old_name='text_img',
            new_name='text_card_img',
        ),
        migrations.AddField(
            model_name='welcome',
            name='text_card',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='welcome',
            name='text_head',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='text',
            field=models.TextField(null=True, verbose_name=''),
        ),
    ]
