# Generated by Django 4.1.3 on 2023-05-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0014_cardtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='latestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_img', models.ImageField(upload_to='images/', verbose_name='Fotoğraf')),
                ('news_text', models.TextField(verbose_name='')),
                ('news_date', models.DateField(verbose_name='Tarih')),
                ('news_img_text', models.TextField(verbose_name='Fotoğraf alt yazı')),
            ],
        ),
    ]
