# Generated by Django 4.1.3 on 2023-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0015_latestnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='news_img',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Fotoğraf'),
        ),
    ]
