# Generated by Django 4.1.3 on 2023-05-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0016_alter_latestnews_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='cardtwo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
